name: Xiang Ji's Webpage
url: http://xiang-ji-ncsu.github.io/
description: A place for some footprints

permalink: /:year/:month/:day/:title/
paginate: 10
pygments: false
highlighter: rouge

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

safe: true

google_analytics: G-V11S3X03Q2

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem